# Generated by Django 3.0.7 on 2020-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('nonce', models.TextField(blank=True)),
            ],
        ),
    ]
